export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const GET_PROFILE = "GET_PROFILE";

export const CREATE_SNAKE_START = "CREATE_SNAKE_START";
export const CREATE_SNAKE_SUCCESS = "CREATE_SNAKE_SUCCESS";
export const CREATE_SNAKE_FAIL = "CREATE_SNAKE_FAIL";
export const CREATE_SNAKE_REMOVE_ERROR = "CREATE_SNAKE_REMOVE_ERROR";

export const GET_SNAKES_START = "GET_SNAKES_START";
export const GET_SNAKES_SUCCESS = "GET_SNAKES_SUCCESS";

export const GET_ONE_SNAKE_START = "GET_ONE_SNAKE_START";
export const GET_ONE_SNAKE_SUCCESS = "GET_ONE_SNAKE_SUCCESS";
