export const header: string;
export const drop: string;
export const logoImage: string;
export const pivot: string;
export const headerItemsWrapper: string;
export const appName: string;
export const userName: string;
export const headerItem: string;
export const ctaButton: string;
